language: node.js
node_js:
  - 12.14.1
cache: yarn

install:
  - yarn install
  - cd client && yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
